### ISSUE TITLE
Lol cheating to get figures on github

### ISSUE THREAD

**Issue by gpleiss** [gpleiss/temperature_scaling#1]
[cifar100-temp.pdf](https://github.com/gpleiss/temperature_scaling/files/1200809/cifar100-temp.pdf)
[cifar100-uncal.pdf](https://github.com/gpleiss/temperature_scaling/files/1200811/cifar100-uncal.pdf)

**Comment by gpleiss** [comment]
![cifar100-temp](https://user-images.githubusercontent.com/824157/28974415-51ae78a8-7904-11e7-9b33-8fbe1f7c0a53.png)
![cifar100-uncal](https://user-images.githubusercontent.com/824157/28974416-51ba7be4-7904-11e7-89ff-3c9b0ec4b607.png)

**Comment by Jordy-VL** [comment]
Hahahaha, love this!
