### ISSUE TITLE
How to make the ECE figure

### ISSUE THREAD

**Issue by zihaolucky** [gpleiss/temperature_scaling#4]
Hi @gpleiss could you give a simple code on the figure in this style?

![ts](https://user-images.githubusercontent.com/4514568/38796619-88fb5b16-418e-11e8-8f19-01b1437596f3.png)

Thanks!

**Comment by gpleiss** [comment]
Sure thing! Give me a day or two to clean up my plotting code and I'll post a gist!

**Comment by zihaolucky** [comment]
@gpleiss Great!

**Comment by zihaolucky** [comment]
I'm trying to reproduce the result in my own application, the ECE could be reduced from 0.016 to 0.008 😂It works but the origin ECE is quite small already.

**Comment by gpleiss** [comment]
Yeah sometimes you get lucky and a model will actually be pretty well calibrated to begin with!

**Comment by zihaolucky** [comment]
I'm working on NLP problem, and I did see the NLL loss growing up during training.

**Comment by zihaolucky** [comment]
By dive into the `(bin_lower, bin_upper, prop_in_bin.data[0], accuracy_in_bin.data[0], avg_confidence_in_bin.data[0]))`, I found the low confidence bin has large error but the ECE is very small as it's a weighted metric. 

The model is still not well calibrated, the final ECE plot is very crucial.

**Comment by skynbe** [comment]
When I try this model to my ResNet, It gives ECE 9.3% -> 4.2%, but the paper shows 16.53% -> 1.26%

**Comment by zihaolucky** [comment]
@gpleiss How this going?

**Comment by gpleiss** [comment]
https://gist.github.com/gpleiss/0b17bc4bd118b49050056cfcd5446c71

This is a rough sketch of how to plot the code. You need all the outputs of a model in a tensor (`outputs`) and the labels.

I haven't run this code, so there's probably a typo in it. But it should give you a rough idea of what to do.

**Comment by zihaolucky** [comment]
@gpleiss Thanks!

**Comment by SophieChang66** [comment]
@zihaolucky hi, this is my network output of the code:
 Before temperature - NLL: 0.075, ECE: 0.013
Optimal temperature: 1.599
After temperature - NLL: 0.062, ECE: 0.010
the original ECE is small, how do you calibrate your network when the ECE is small ?

**Comment by gpleiss** [comment]
@SophieChang66 if your ECE is small, then it is well calibrated already :)
